"use client"

import { useState } from "react"

type PrescriptionMedicine = {
  name: string
  generic_name: string | null
  dosage: string | null
  frequency: string | null
  duration: string | null
  instructions: string | null
}

type Prescription = {
  patient_name: string | null
  patient_age: string | null
  doctor_name: string | null
  clinic: string | null
  date: string | null
  diagnosis: string | null
  medicines: PrescriptionMedicine[]
  notes: string | null
  confidence: "high" | "medium" | "low"
}

const confidenceConfig = {
  high:   { label: "High Confidence",   color: "bg-emerald-100 text-emerald-700 border-emerald-200" },
  medium: { label: "Medium Confidence", color: "bg-amber-100 text-amber-700 border-amber-200" },
  low:    { label: "Low Confidence",    color: "bg-red-100 text-red-700 border-red-200" },
}

function printPrescription(prescription: Prescription) {
  const date = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })

  const medicineRows = prescription.medicines.map((med, i) => `
    <tr>
      <td class="num">${i + 1}</td>
      <td>
        <strong>${med.name}</strong>
        ${med.generic_name ? `<br/><span class="generic">${med.generic_name}</span>` : ""}
      </td>
      <td>${med.dosage ?? "—"}</td>
      <td>${med.frequency ?? "—"}</td>
      <td>${med.duration ?? "—"}</td>
      <td>${med.instructions ?? "—"}</td>
    </tr>
  `).join("")

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Prescription</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; font-size: 13px; color: #1e293b; padding: 36px 44px; }

    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
    .brand { font-size: 22px; font-weight: 900; color: #1e293b; letter-spacing: -0.5px; }
    .brand span { color: #2563eb; }
    .meta { text-align: right; font-size: 11px; color: #64748b; line-height: 1.6; }

    .section-title { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 10px; }

    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    thead tr { background: #f1f5f9; }
    th { padding: 9px 12px; text-align: left; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: #64748b; border-bottom: 1px solid #e2e8f0; }
    td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; vertical-align: top; line-height: 1.5; }
    td.num { color: #94a3b8; font-size: 11px; width: 28px; }
    .generic { font-style: italic; color: #64748b; font-size: 11px; }
    tr:last-child td { border-bottom: none; }

    .notes-box { background: #fffbeb; border: 1px solid #fcd34d; border-radius: 6px; padding: 12px 16px; margin-bottom: 24px; }
    .notes-box .label { font-size: 10px; font-weight: 700; text-transform: uppercase; color: #92400e; margin-bottom: 4px; }
    .notes-box p { color: #78350f; font-size: 12px; line-height: 1.6; }

    .confidence { display: inline-block; font-size: 10px; font-weight: 700; padding: 3px 10px; border-radius: 999px; border: 1px solid; }
    .confidence.high   { background: #d1fae5; color: #065f46; border-color: #6ee7b7; }
    .confidence.medium { background: #fef3c7; color: #92400e; border-color: #fcd34d; }
    .confidence.low    { background: #fee2e2; color: #991b1b; border-color: #fca5a5; }

    .footer { margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 14px; display: flex; justify-content: space-between; align-items: center; font-size: 11px; color: #94a3b8; }
    @media print { body { padding: 20px 28px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">Uni<span>pharma</span></div>
      <div style="font-size:11px;color:#64748b;margin-top:3px;">AI-Parsed Prescription</div>
    </div>
    <div class="meta">
      Printed: ${date}<br/>
      <span class="confidence ${prescription.confidence}">${confidenceConfig[prescription.confidence].label}</span>
    </div>
  </div>

  <div class="section-title">Prescribed Medicines</div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Medicine</th>
        <th>Dosage</th>
        <th>Frequency</th>
        <th>Duration</th>
        <th>Instructions</th>
      </tr>
    </thead>
    <tbody>${medicineRows}</tbody>
  </table>

  ${prescription.notes ? `
  <div class="notes-box">
    <div class="label">Notes</div>
    <p>${prescription.notes}</p>
  </div>` : ""}

  <div class="footer">
    <span>Generated by Unipharma Smart Rx Scanner</span>
    <span>This is an AI-assisted summary — verify with original prescription</span>
  </div>
</body>
</html>`

  const win = window.open("", "_blank", "width=900,height=700")
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => { win.print() }, 500)
}

export default function Prescription() {
  const [ocrText, setOcrText]           = useState("")
  const [prescription, setPrescription] = useState<Prescription | null>(null)
  const [error, setError]               = useState("")
  const [ocrLoading, setOcrLoading]     = useState(false)
  const [aiLoading, setAiLoading]       = useState(false)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)

  async function upload(file: File) {
    setOcrLoading(true)
    setAiLoading(false)
    setError("")
    setOcrText("")
    setPrescription(null)

    try {
      const form = new FormData()
      form.append("file", file)
      const ocrRes = await fetch("/api/open-router", { method: "POST", body: form })
      const ocrData = await ocrRes.json()

      if (ocrData.error) { setError(ocrData.error); return }

      const extracted: string = ocrData.text || ""
      setOcrText(extracted)
      setOcrLoading(false)

      if (!extracted.trim()) {
        setError("No text could be extracted. Please try a clearer photo.")
        return
      }

      setAiLoading(true)
      const aiRes = await fetch("/api/gemini-prescription", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: extracted }),
      })
      const aiData = await aiRes.json()

      if (aiData.error) { setError(aiData.error); return }
      setPrescription(aiData.prescription)
    } catch {
      setError("An unexpected error occurred. Please try again.")
    } finally {
      setOcrLoading(false)
      setAiLoading(false)
    }
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (file) { setSelectedFile(file); upload(file) }
  }

  const isLoading = ocrLoading || aiLoading
  const loadingLabel = ocrLoading ? "Reading prescription image…" : "Analysing with AI…"

  return (
    <div className="space-y-5">

      {/* Upload zone */}
      <label className="block p-8 border-2 border-dashed border-blue-400/60 rounded-xl text-center cursor-pointer hover:border-blue-400 hover:bg-white/5 transition-colors">
        <input type="file" accept="image/*,.pdf" onChange={handleFileChange} className="hidden" />
        <div className="flex flex-col items-center gap-2">
          <svg className="w-8 h-8 text-blue-400 opacity-80" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
          </svg>
          <span className="text-sm font-medium text-blue-300">
            {selectedFile ? selectedFile.name : "Click to upload prescription"}
          </span>
          <span className="text-xs text-blue-400/60">PNG, JPG, PDF</span>
        </div>
      </label>

      {/* Loading */}
      {isLoading && (
        <div className="flex items-center gap-3 rounded-xl bg-white/10 px-4 py-3">
          <div className="h-4 w-4 animate-spin rounded-full border-2 border-blue-300 border-t-transparent flex-shrink-0" />
          <span className="text-sm text-blue-200">{loadingLabel}</span>
        </div>
      )}

      {/* Error */}
      {error && !isLoading && (
        <div className="rounded-xl bg-red-500/20 border border-red-400/30 px-4 py-3 flex items-start gap-3">
          <svg className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01M5.07 19h13.86c1.54 0 2.5-1.67 1.73-3L13.73 4c-.77-1.33-2.69-1.33-3.46 0L3.34 16c-.77 1.33.19 3 1.73 3z" />
          </svg>
          <div className="flex-1">
            <p className="text-sm text-red-300">{error}</p>
            {selectedFile && (
              <button onClick={() => upload(selectedFile)} className="mt-2 text-xs font-semibold text-red-400 hover:text-red-300 underline">
                Try again
              </button>
            )}
          </div>
        </div>
      )}

      {/* Result */}
      {prescription && !isLoading && (
        <div className="space-y-4">

          {/* Title row + Download button */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <p className="text-xs font-semibold uppercase tracking-wider text-blue-300">Medicines</p>
              <span className={`text-xs font-bold px-2.5 py-1 rounded-full border ${confidenceConfig[prescription.confidence].color}`}>
                {confidenceConfig[prescription.confidence].label}
              </span>
            </div>
            <button
              onClick={() => printPrescription(prescription)}
              className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 text-xs font-semibold text-white transition"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download / Print
            </button>
          </div>

          {/* Medicine cards */}
          {prescription.medicines?.length > 0 ? (
            <div className="space-y-3">
              {prescription.medicines.map((med, i) => (
                <div key={i} className="rounded-xl bg-white/10 border border-white/10 p-4">
                  <div className="flex items-start justify-between gap-2 mb-3">
                    <div>
                      <p className="font-bold text-white">{med.name}</p>
                      {med.generic_name && (
                        <p className="text-xs italic text-blue-300 mt-0.5">{med.generic_name}</p>
                      )}
                    </div>
                    {med.dosage && (
                      <span className="flex-shrink-0 text-xs font-bold bg-blue-500/30 text-blue-200 border border-blue-400/30 px-2.5 py-1 rounded-full">
                        {med.dosage}
                      </span>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    {med.frequency && <MedTag icon="🕐" label="Frequency" value={med.frequency} />}
                    {med.duration  && <MedTag icon="📆" label="Duration"  value={med.duration} />}
                    {med.instructions && (
                      <div className="col-span-2">
                        <MedTag icon="💡" label="Instructions" value={med.instructions} />
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-slate-400 italic">No medicines detected.</p>
          )}

          {/* Notes */}
          {prescription.notes && (
            <div className="rounded-xl bg-amber-500/10 border border-amber-400/20 p-4">
              <p className="text-xs font-semibold text-amber-400 mb-1">Notes</p>
              <p className="text-sm text-amber-100">{prescription.notes}</p>
            </div>
          )}

          {/* Raw OCR toggle */}
          <details>
            <summary className="cursor-pointer text-xs text-blue-400/60 hover:text-blue-400 transition-colors select-none">
              Show raw OCR text
            </summary>
            <pre className="mt-2 rounded-lg bg-black/30 p-3 text-xs text-slate-400 leading-5 whitespace-pre-wrap overflow-auto max-h-40">
              {ocrText}
            </pre>
          </details>

        </div>
      )}
    </div>
  )
}

function MedTag({ icon, label, value }: { icon: string; label: string; value: string }) {
  return (
    <div className="rounded-lg bg-black/20 px-3 py-2">
      <p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{icon} {label}</p>
      <p className="text-sm text-slate-200 mt-0.5">{value}</p>
    </div>
  )
}
