import type { Metadata } from 'next'
import {
  ClerkDegraded,
  ClerkFailed,
  ClerkLoaded,
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default:"Smart Warehouse",
    template:"%s| Smart Warehouse"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <ClerkLoaded>
              <Show when="signed-out">
                <SignInButton>
                  <SignText displayText='Sign In' />
                </SignInButton>

                <SignUpButton>
                  <SignText displayText='Sign Up' />
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </ClerkLoaded>

            <ClerkFailed>
              <AuthUnavailableNotice />
            </ClerkFailed>

            <ClerkDegraded>
              <AuthUnavailableNotice />
            </ClerkDegraded>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}

function SignText({displayText}:{displayText:string}){
  return <p className='bg-green-400 py-2 px-4 rounded-lg cursor-pointer'>{displayText}</p>
}

function AuthUnavailableNotice() {
  return (
    <p className="rounded-lg bg-amber-100 px-4 py-2 text-sm font-medium text-amber-800">
      Auth temporarily unavailable
    </p>
  );
}
